/**
 * Alumni model types and constants
 *
 * Update this file to reflect the exact Supabase table schema for Alumni.
 * Keep names/types in sync with your database columns.
 */

export const ALUMNI_TABLE = "Alumni" as const; // TODO: Confirm exact table name in Supabase

/**
 * Columns used by the application excluding autogenerated fields (id, created_at).
 * Replace with your actual columns and types.
 */
export interface AlumniFields {
  // Matches Supabase columns per provided example
  profile_url?: string | null;
  full_name?: string | null;
  emails?: string[] | null;
  phone?: string | null;
  linkedin_url?: string | null;
  instagram_url?: string | null;
  graduation_year?: string | null; // Stored as enum in Supabase
  major?: string | null;
  location?: string | null;
  skills?: string[] | null;
  interests?: string[] | null;
  bio?: string | null;
  updated_at?: string | null;
}

/**
 * Row returned by the API after inserts/reads.
 */
export interface AlumniRecord extends AlumniFields {
  id: string;
  created_at: string;
}

/**
 * Raw row shape as stored in Supabase (snake_case if applicable).
 * Adjust to match your actual storage casing and optionality.
 */
export interface SupabaseAlumniRow {
  id: string;
  profile_url?: string | null;
  full_name?: string | null;
  emails?: string[] | null;
  phone?: string | null;
  linkedin_url?: string | null;
  instagram_url?: string | null;
  graduation_year?: string | null;
  major?: string | null;
  location?: string | null;
  skills?: string[] | null;
  interests?: string[] | null;
  bio?: string | null;
  created_at: string;
  updated_at?: string | null;
}

/**
 * List of URL-like fields that should be excluded from /alumni/query filters.
 * Keep this list in sync with your schema.
 */
export const alumniUrlFields: readonly string[] = [
  "profile_url",
  "linkedin_url",
  "instagram_url",
];
